In [116]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn import metrics

In [78]:
X = pd.read_csv("./data/X.csv")

In [79]:
X.shape

(213466, 150)

In [3]:
data_countries = pd.read_csv("./data/countries.csv")

In [27]:
print data_countries

  country_destination  lat_destination  lng_destination  distance_km  \
0                  AU       -26.853388       133.275160   15297.7440   
1                  CA        62.393303       -96.818146    2828.1333   
2                  DE        51.165707        10.452764    7879.5680   
3                  ES        39.896027        -2.487694    7730.7240   
4                  FR        46.232193         2.209667    7682.9450   
5                  GB        54.633220        -3.432277    6883.6590   
6                  IT        41.873990        12.564167    8636.6310   
7                  NL        52.133057         5.295250    7524.3203   
8                  PT        39.553444        -7.839319    7355.2534   
9                  US        36.966427       -95.844030       0.0000   

   destination_km2 destination_language   language_levenshtein_distance  
0          7741220                   eng                           0.00  
1          9984670                   eng                   

### Init X_countries

In [58]:
X_countries = pd.core.frame.DataFrame()
X_countries["country_destination"] = data_countries["country_destination"]
X_countries["language_levenshtein_distance"] = data_countries["language_levenshtein_distance"]

### Normalize distance_km

In [59]:
# Create x, where x the 'scores' column's values as floats
x = data_countries['distance_km'].values.astype(float)

# Create a minimum and maximum processor object
min_max_scaler = preprocessing.MinMaxScaler()

# Create an object to transform the data to fit minmax processor
x_scaled = min_max_scaler.fit_transform(x)

# Run the normalizer on the dataframe
X_countries["distance_km"] = x_scaled


//anaconda/lib/python2.7/site-packages/sklearn/preprocessing/data.py:324: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
//anaconda/lib/python2.7/site-packages/sklearn/preprocessing/data.py:359: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


### Normalize destination_km2

In [60]:
# Create x, where x the 'scores' column's values as floats
x = data_countries['destination_km2'].values.astype(float)

# Create a minimum and maximum processor object
min_max_scaler = preprocessing.MinMaxScaler()

# Create an object to transform the data to fit minmax processor
x_scaled = min_max_scaler.fit_transform(x)

# Run the normalizer on the dataframe
X_countries["destination_km2"] = x_scaled

//anaconda/lib/python2.7/site-packages/sklearn/preprocessing/data.py:324: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
//anaconda/lib/python2.7/site-packages/sklearn/preprocessing/data.py:359: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


### Normalize language_levenshtein_distance

In [67]:
x = data_countries['language_levenshtein_distance'].values.astype(float)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
X_countries["language_levenshtein_distance"] = x_scaled

//anaconda/lib/python2.7/site-packages/sklearn/preprocessing/data.py:324: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
//anaconda/lib/python2.7/site-packages/sklearn/preprocessing/data.py:359: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


In [179]:
X_countries

country_destination  language_levenshtein_distance  distance_km  \
0                  AU                       0.000000     1.000000   
1                  CA                       0.000000     0.184873   
2                  DE                       0.760712     0.515080   
3                  ES                       0.966475     0.505351   
4                  FR                       0.964484     0.502227   
5                  GB                       0.000000     0.449979   
6                  IT                       0.936616     0.564569   
7                  NL                       0.662336     0.491858   
8                  PT                       1.000000     0.480806   
9                  US                       0.000000     0.000000   

   destination_km2  population_in_thousands  population_in_thousands_norm  \
0         0.774372                    23923                      0.042331   
1         1.000000                    35871                      0.080318   
2         0.031728                    82562                      0.228769   
3         0.046648                    47203                      0.116348   
4         0.060570                    64983                      0.172878   
5         0.020322                    63840                      0.169244   
6         0.026128                    61145                      0.160675   
7         0.000000                    16848                      0.019836   
8         0.005084                    10609                      0.000000   
9         0.984110                   325132                      1.000000   

   avg_monthly_search_volumes  avg_monthly_search_volumes_norm  
0                      301000                         0.489744  
1                      246000                         0.348718  
2                      246000                         0.348718  
3                      165000                         0.141026  
4                      201000                         0.233333  
5                      150000                         0.102564  
6                      201000                         0.233333  
7                      110000                         0.000000  
8                      110000                         0.000000  
9                      500000                         1.000000

In [47]:
data_age_gender_bkts = pd.read_csv("./data/age_gender_bkts.csv")

### Set population_in_thousands

In [62]:
pops = []
for country in X_countries.country_destination.values:
    print "country: %s, popul: %d" % (country, sum(data_age_gender_bkts[data_age_gender_bkts.country_destination == country].population_in_thousands.values))
    pops.append(sum(data_age_gender_bkts[data_age_gender_bkts.country_destination == country].population_in_thousands.values))

country: AU, popul: 23923
country: CA, popul: 35871
country: DE, popul: 82562
country: ES, popul: 47203
country: FR, popul: 64983
country: GB, popul: 63840
country: IT, popul: 61145
country: NL, popul: 16848
country: PT, popul: 10609
country: US, popul: 325132


In [63]:
X_countries["population_in_thousands"] = pops

### Set population_in_thousands_norm

In [77]:
x = X_countries['population_in_thousands'].values.astype(float)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x.reshape(-1,1))
X_countries["population_in_thousands_norm"] = x_scaled

## Set search volume (from US) for each country by Google keyword tool

In [103]:
X_countries.country_destination

0    AU
1    CA
2    DE
3    ES
4    FR
5    GB
6    IT
7    NL
8    PT
9    US
Name: country_destination, dtype: object

In [105]:
avg_monthly_search_volumes = [301000, 246000, 246000, 165000, 201000, 110000+40000, 201000, 110000, 110000, 500000]
#                             AU      CA      DE      ES      FR      GB            IT      NL      PT      US
X_countries["avg_monthly_search_volumes"] = avg_monthly_search_volumes

x = X_countries['avg_monthly_search_volumes'].values.astype(float)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x.reshape(-1,1))
X_countries["avg_monthly_search_volumes_norm"] = x_scaled

## Set country attributes for X

In [81]:
# to test:
#X_test = X[:100]
#X_test.shape

(100, 150)

In [106]:
for country in X_countries.country_destination.values:
    #print "country: %s, language_levenshtein_distance: %s" % (country, [X_countries[X_countries.country_destination==country].language_levenshtein_distance.values])
    X["language_levenshtein_distance_%s"%country] = np.array([X_countries[X_countries.country_destination==country].language_levenshtein_distance.values] * len(X))
    X["distance_km_%s"%country] = np.array([X_countries[X_countries.country_destination==country].distance_km.values] * len(X))
    X["destination_km2_%s"%country] = np.array([X_countries[X_countries.country_destination==country].destination_km2.values] * len(X))
    X["population_in_thousands_norm_%s"%country] = np.array([X_countries[X_countries.country_destination==country].population_in_thousands_norm.values] * len(X))
    X["avg_monthly_search_volumes_norm_%s"%country] = np.array([X_countries[X_countries.country_destination==country].avg_monthly_search_volumes_norm.values] * len(X))
    

In [188]:
X.shape

(213466, 210)

In [177]:
## TEST
#for country in X_countries.country_destination.unique():
#    print "country: %s, age:%s, pop:%d" % (country, "100+", sum(data_age_gender_bkts[(data_age_gender_bkts.age_bucket=="100+") & (data_age_gender_bkts.country_destination==country)].population_in_thousands))

country: AU, age:100+, pop:5
country: CA, age:100+, pop:8
country: DE, age:100+, pop:17
country: ES, age:100+, pop:12
country: FR, age:100+, pop:22
country: GB, age:100+, pop:16
country: IT, age:100+, pop:18
country: NL, age:100+, pop:2
country: PT, age:100+, pop:1
country: US, age:100+, pop:74


### Set age_bucket_perc_XX attributes

In [187]:
#x_t = X.loc[:10, ["age", ""]]
#x_t["age_group"] = [None] * (len(x_t))
#x_t.loc[0, "age"] = 55
#print "initial x_t:\n",x_t

def set_age_gender(row):
    if row.age == 0:
        #print "age is zero, returning.."
        return 0
    if row.age > 99:
        age_bucket = "100+"
    else:
        age_bucket = "%d-%d" % (row.age - row.age%5, row.age + (4-row.age%5))
    #row.age_group = "%d-%d" % (row.age - row.age%5, row.age + (4-row.age%5))
    #print "age is %d, setting it to %s" % (row.age, row.age_group)
    #age_bucket_pop = sum(data_age_gender_bkts[(data_age_gender_bkts.age_bucket==age_bucket) & (data_age_gender_bkts.country_destination==country)].population_in_thousands)
    return sum(data_age_gender_bkts[(data_age_gender_bkts.age_bucket==age_bucket) & (data_age_gender_bkts.country_destination==country)].population_in_thousands)
    #country_pop = X_countries[X_countries.country_destination==country].population_in_thousands
    #return age_bucket_pop/float(country_pop)
    #return age_bucket_pop

for country in X_countries.country_destination.unique():
    country_pop = X_countries[X_countries.country_destination==country].population_in_thousands
    X["age_bucket_perc_%s"%country] = X.apply(set_age_gender, axis=1)/float(country_pop)

#print "processed x_t:\n",x_t

## (Optional) split to train and test sets

In [189]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=1)

In [190]:
print X_train.shape
print y_train.shape
print X_test.shape
print y_test.shape

(149426, 210)
(149426,)
(64040, 210)
(64040,)


## TEST new attrs's relevance to perf w ADABoosting (n_estimators=100): 0.6329 (no change)
## TEST new attrs's relevance to perf w ADABoosting (n_estimators=120): 0.6331 

In [126]:
from sklearn.ensemble import AdaBoostClassifier

abo = AdaBoostClassifier(n_estimators=120)
abo.fit(X_train, y_train.astype(int))
y_pred_abo = abo.predict(X_test)

In [127]:
print metrics.accuracy_score(y_test.astype(int), y_pred_abo.astype(int))

0.633104309806


In [128]:
conf_matrix_abo = metrics.confusion_matrix(y_test.astype(int), y_pred_abo.astype(int))
print conf_matrix_abo
print sum(sum(conf_matrix_abo))

[[32141  5168     0     0     0     0     0     0     0     0     0     0]
 [10387  8403     0     0     0     0     0     0     0     0     0     0]
 [ 1754  1231     0     0     0     0     0     0     0     0     0     0]
 [  868   627     0     0     0     0     0     0     0     0     0     0]
 [  234   204     0     0     0     0     0     0     0     0     0     0]
 [  391   324     0     0     0     0     0     0     0     0     0     0]
 [  394   282     0     0     0     0     0     0     0     0     0     0]
 [  506   372     0     0     0     0     0     0     0     0     0     0]
 [   44    21     0     0     0     0     0     0     0     0     0     0]
 [  124   108     0     0     0     0     0     0     0     0     0     0]
 [  158   135     0     0     0     0     0     0     0     0     0     0]
 [   76    88     0     0     0     0     0     0     0     0     0     0]]
64040


In [119]:
feat_importances = []
for i in range(len(X_test.columns)):
    #print "%s: %.3f" % (X_test.columns[i], abo.feature_importances_[i])
    feat_importances.append((X_test.columns[i], abo.feature_importances_[i]))

feat_importances = sorted(feat_importances, key=lambda x: x[1], reverse=True)
for pair in feat_importances:
    print pair[0], pair[1]

age 0.17
month_acct_created 0.09
gender_MALE 0.02
signup_flow_23 0.02
aff_chnl_other 0.02
first_aff_tracked_tracked_other 0.02
gender__unknown_ 0.01
gender_OTHER 0.01
signup_basic 0.01
signup_google 0.01
signup_flow_0 0.01
signup_flow_3 0.01
signup_flow_2 0.01
signup_flow_1 0.01
signup_flow_8 0.01
signup_flow_6 0.01
signup_flow_12 0.01
signup_flow_16 0.01
signup_flow_15 0.01
signup_flow_21 0.01
language_fr 0.01
language_de 0.01
language_es 0.01
language_it 0.01
language_pt 0.01
language_zh 0.01
language_ko 0.01
language_ja 0.01
language_ru 0.01
language_pl 0.01
language_el 0.01
language_nl 0.01
language_da 0.01
aff_chnl_seo 0.01
aff_chnl_sem_non_brand 0.01
aff_chnl_content 0.01
aff_chnl_sem_brand 0.01
aff_chnl_remarketing 0.01
aff_prov_craigslist 0.01
aff_prov_facebook 0.01
aff_prov_vast 0.01
aff_prov_bing 0.01
aff_prov_meetup 0.01
aff_prov_facebook_open_graph 0.01
aff_prov_email_marketing 0.01
aff_prov_yahoo 0.01
aff_prov_padmapper 0.01
aff_prov_gsp 0.01
first_aff_tracked_untracked 0.

## TEST new attr's perf w XGBoosting(max_depth=2): 0.6368 (no change)

In [205]:
import xgboost as xgb

#param = {'bst:max_depth':2, 'bst:eta':1, 'silent':1, 'objective':'binary:logistic' }
param = {'bst:max_depth':2, 'bst:eta':1, 'silent':0, 'objective': 'multi:softmax', 'num_class': 12}
param['nthread'] = 4
#param['eval_metric'] = 'auc'
num_round = 150
dtrain = xgb.DMatrix( X_train, label=y_train )
dtest = xgb.DMatrix( X_test, label=y_test )
evallist  = [(dtest,'eval'), (dtrain,'train')]
#bst = xgb.train( param.items(), dtrain, num_round, evallist, early_stopping_rounds=10)
bst = xgb.train( param.items(), dtrain, num_round, evallist)

[0]	eval-merror:0.369878	train-merror:0.370612
[1]	eval-merror:0.626390	train-merror:0.623339
[2]	eval-merror:0.368723	train-merror:0.369521
[3]	eval-merror:0.368239	train-merror:0.368999
[4]	eval-merror:0.367302	train-merror:0.368283
[5]	eval-merror:0.367473	train-merror:0.367928
[6]	eval-merror:0.367364	train-merror:0.367386
[7]	eval-merror:0.367146	train-merror:0.367352
[8]	eval-merror:0.366084	train-merror:0.366937
[9]	eval-merror:0.366240	train-merror:0.366817
[10]	eval-merror:0.366099	train-merror:0.366703
[11]	eval-merror:0.365896	train-merror:0.366382
[12]	eval-merror:0.365912	train-merror:0.365994
[13]	eval-merror:0.366099	train-merror:0.365873
[14]	eval-merror:0.365662	train-merror:0.365753
[15]	eval-merror:0.365272	train-merror:0.365572
[16]	eval-merror:0.365475	train-merror:0.365766
[17]	eval-merror:0.365334	train-merror:0.365800
[18]	eval-merror:0.365522	train-merror:0.365753
[19]	eval-merror:0.365709	train-merror:0.365425
[20]	eval-merror:0.365600	train-merror:0.365505
[2

In [203]:
y_pred_xgb = bst.predict(xgb.DMatrix(X_test))

In [204]:
print metrics.accuracy_score(y_test.astype(int), y_pred_xgb.astype(int))

0.618566520924


In [198]:
conf_matrix_xgb = metrics.confusion_matrix(y_test.astype(int), y_pred_xgb.astype(int))
print conf_matrix_xgb
print sum(sum(conf_matrix_xgb))

[[31351  5721    77    39    18    26    14    23    11     5    14    10]
 [ 9788  8743    70    38    18    19    18    32     4    21    27    12]
 [ 1667  1258    22    10     1     1     5     6     2     3     7     3]
 [  831   640     6     3     1     1     2     4     0     1     4     2]
 [  229   205     2     0     0     1     0     0     0     0     0     1]
 [  374   326     2     2     1     0     2     2     1     3     0     2]
 [  389   283     1     1     0     0     0     0     0     1     1     0]
 [  479   381     4     0     1     3     3     3     1     1     1     1]
 [   42    22     0     1     0     0     0     0     0     0     0     0]
 [  115   111     1     3     0     0     0     1     0     0     0     1]
 [  156   134     1     1     0     0     0     0     0     0     1     0]
 [   88    74     1     1     0     0     0     0     0     0     0     0]]
64040


## TEST new attrs relevance to performance w FNN: 0.6336 (~no change)

In [99]:
y = pd.read_csv("./data/y.csv")
y_labels = {}
i = 0
for value in y.country_destination.unique():
    if value not in y_labels.keys():
        y_labels[value] = i
        i += 1
    y[y == value] = i-1

print "y is indexed by dict:\n%s" % y_labels

y = y.country_destination
y.ravel().astype(int)

y is indexed by dict:
{'FR': 3, 'NL': 9, 'PT': 8, 'CA': 4, 'DE': 10, 'IT': 7, 'US': 1, 'NDF': 0, 'other': 2, 'AU': 11, 'GB': 5, 'ES': 6}


array([0, 0, 1, ..., 5, 9, 0])

In [108]:
print X.shape
print y.shape

(213466, 200)
(213466,)


In [102]:
from pybrain.tools.shortcuts import buildNetwork
from pybrain.structure import TanhLayer
from pybrain.structure import SoftmaxLayer
from pybrain.datasets import ClassificationDataSet
from pybrain.supervised.trainers import BackpropTrainer
from pybrain.utilities import percentError

alldata = ClassificationDataSet(190, 1, nb_classes=12)
for i in range(X.shape[0]):
    alldata.addSample(X[i:i+1].values.tolist()[0], y[i:i+1].values.tolist())

tstdata, trndata = alldata.splitWithProportion( 0.3 )

trndata._convertToOneOfMany( )
tstdata._convertToOneOfMany( )

#net = buildNetwork(150, 100, 50, 12, 1, bias=True, hiddenclass=TanhLayer, outclass=SoftmaxLayer)
#fnn = buildNetwork( trndata.indim, 20, 20, 20, 20, 20, trndata.outdim, bias=True, hiddenclass=TanhLayer, outclass=SoftmaxLayer ) # yields %45.62 test error
fnn = buildNetwork( trndata.indim, 100, 70, 50, 30, 20, trndata.outdim, outclass=SoftmaxLayer)
                   
#trainer = BackpropTrainer( fnn, dataset=trndata, momentum=0.1, verbose=True, weightdecay=0.01) 
trainer = BackpropTrainer( fnn, dataset=trndata, verbose=True) 

for i in range(30):
    trainer.trainEpochs( 1 )
    trnresult = percentError( trainer.testOnClassData(),
                              trndata['class'] )
    tstresult = percentError( trainer.testOnClassData(
           dataset=tstdata ), tstdata['class'] )

    print "epoch: %4d" % trainer.totalepochs, \
          "  train error: %5.2f%%" % trnresult, \
          "  test error: %5.2f%%" % tstresult    

Total error: 0.0222906200351
epoch:    1   train error: 43.02%   test error: 42.67%
Total error: 0.0218670071775
epoch:    2   train error: 37.70%   test error: 37.70%
Total error: 0.0217072342001
epoch:    3   train error: 38.33%   test error: 38.05%
Total error: 0.0216119301224
epoch:    4   train error: 37.29%   test error: 37.24%
Total error: 0.0215218468419
epoch:    5   train error: 39.08%   test error: 38.96%
Total error: 0.0214592080769
epoch:    6   train error: 37.52%   test error: 37.44%
Total error: 0.0214182464879
epoch:    7   train error: 37.03%   test error: 36.97%
Total error: 0.0214048940655
epoch:    8   train error: 36.91%   test error: 36.81%
Total error: 0.0213679257671
epoch:    9   train error: 39.13%   test error: 39.10%
Total error: 0.0213744067891
epoch:   10   train error: 37.18%   test error: 37.26%
Total error: 0.0213652807028
epoch:   11   train error: 37.28%   test error: 37.41%
Total error: 0.0213507612538
epoch:   12   train error: 37.58%   test error: